# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: uv.esavi
canonical: https://paho.org/fhir/esavi
name: ESAVI
status: draft
version: 0.1.45
fhirVersion: 4.0.1
title: ESAVI FHIR Implementation Guide (IG)
copyrightYear: 2021+
releaseLabel: ci-build
#language: es-AR

jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
publisher:
  name: ESAVI -
  url: https://covid-19pharmacovigilance.paho.org/resources/updates-on-aefi
  email: rizzatodan@paho.org

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰───────────────────────────────────────────────────────────────────────────────────────────────╯

pages:
  index.md:
    title: Home
  objetivos.md:
    title: Objetives
  alcance.md:
    title: Scope
  uso.md:
    title: How to complete IG
  transactions.md:
    title: Transaction
  actores_CasosUso.md:
    title: Uses cases and actors
  artifacts.html:
    title: Artifacts
  mapeos.md:
    title:  Mappings
  terminologias.md:
    title: Terminologies
  descargas.md:
    title: Downloads
  generalidades.md:
    title: Generalities
  consideraciones.md:
    title: Considerations
  operaciones.md:
    title: Operations
  seguridad.md:
    title: Security

menu:
  Home: index.html
  Objetives: objetivos.html
  Scope: alcance.html
  Usage: uso.html
  Transaction: transactions.html
  Uses cases and actors: actores_CasosUso.html
  Artifacts: artifacts.html
  Mapping: mapeos.html
  #  Seguridad: seguridad.html
  Terminologies: terminologias.html
  Downloads: descargas.html
  Generalities: generalidades.html
  Considerations: consideraciones.html
  #Datos Generales:
  #  Generalidades: generalidades.html
  #  Actores y Casos de Uso: actores_CasosUso.html
  #  Operaciones FHIR: operaciones.html